# Configuration Netlify (optionnel)
# Pour d√©ployer sur Netlify au lieu de GitHub Pages

[build]
  command = "npm run build:prod"
  publish = "dist/szkole/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

